@server=http://localhost:8080
@username=admin
@password=admin


### SerialData
# @name SerialData_GET
GET {{server}}/odata/v4/SerialService/SerialData
Authorization: Basic {{username}}:{{password}}


### SerialData
# @name SerialData_POST
POST {{server}}/odata/v4/SerialService/SerialData
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
  "s4Key": "SerialData-16687225",
  "plant": "7225",
  "status": "s-16687225",
  "serialNo": "serialNo-16687225",
  "dataType": "25",
  "registrationDate": "2014-07-17"
}


### SerialData
# @name SerialData_PATCH
PATCH {{server}}/odata/v4/SerialService/SerialData/SerialData-16687225
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
  "s4Key": "SerialData-16687225",
  "plant": "7225",
  "status": "s-16687225",
  "serialNo": "serialNo-16687225",
  "dataType": "25",
  "registrationDate": "2014-07-17"
}


### SerialData
# @name SerialData_DELETE
DELETE {{server}}/odata/v4/SerialService/SerialData/SerialData-16687225
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}
